### ISSUE TITLE
Address to Scripthash

### ISSUE THREAD

**Issue by steven1227** [CityOfZion/neo-mamba#79]
Hey Guys, Recently I am importing neo-mamba as SDK in a python script. However, I can not find toScripthash as in [C# helper](https://github.com/neo-project/neo/blob/master/src/neo/Wallets/Helper.cs#L46). How can I use it?

**Comment by ixje** [comment]
```python
from neo3.core import to_script_hash
```

**Comment by steven1227** [comment]
> ```python
> from neo3.core import to_script_hash
> ```

Thanks man. Is it possible to update more in the docs? I tried to find in docs but looks like not that easy.

**Comment by steven1227** [comment]
and @ixje  I found it is just a bytes to hash160, not specific address to scripthash, isn't it?

**Comment by ixje** [comment]
That is correct. Your "address to script hash" function doesn't exist yet. It will be part of https://github.com/CityOfZion/neo-mamba/pull/75

Documentation will be updated after we catch up to RC1/RC2. We had to decide on
1. Catching up with the C# implementation slow, but have full and elaborate documentation
2. Catching up with C# faster, but have limited/less documentation.

It made more sense to have an SDK that works with the latest N3 version with less documentation, than have an SDK that is not compatible with the latest N3 version but has full documentation. Also since so much changes every release it would be wasting a lot of effort and resources on updating documentation that will is obsolete shortly after. That's also not every energizing work todo

**Comment by ixje** [comment]
It's part of the `feature-wallet` branch. 
https://github.com/CityOfZion/neo-mamba/blob/55e078eea536f6c31b289bb3b353c709ef737565/neo3/wallet/account.py#L149
